### ISSUE TITLE
Add multimodal support for the new ChatMessage class

### ISSUE THREAD

**Issue by LastRemote** [deepset-ai/haystack-experimental#135]
This is a to-do for myself to add multimodal supports (image, audio and pdf for OpenAI and Anthropic models) in the experimental implementation of ChatMessage according to https://github.com/deepset-ai/haystack/issues/7848#issuecomment-2406323269

Will open a draft PR later this week.
```[tasklist]
### Tasks
- [x] Update ByteStream to support automatically loading mime_type
- [x] Add a new MediaContent to ChatMessageContentT
- [x] Serialization & Deserialization for ChatMessage and ByteStream
- [x] Update message_to_openai_format
- [x] Update message_to_anthropic_format
- [x] Create a draft PR
```

**Comment by LastRemote** [comment]
Sorry for the wait. Here it is: https://github.com/deepset-ai/haystack-experimental/pull/145
